apiVersion: v1
kind: Service
metadata:
  name: guess-svc
spec:
  type: NodePort
  selector:
    app: guess-app
  ports:
    - protocol: TCP
      nodePort: 30036
      port: 5005
      targetPort: 5000